package com.mycompany.crud.app.java;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class FormPersonal extends javax.swing.JFrame {

    public FormPersonal() {
        initComponents();
        llenarEstados();
        
        this.setLocationRelativeTo(null);
        txtId.setEnabled(false);
     
        CPersonal objetoAlumnos = new CPersonal();
        objetoAlumnos.MostrarPersonal(tbTotalPersonal);
    }
    
    private void llenarEstados(){
        CPersonal personal = new CPersonal();
        ArrayList<CEstado> listaEstado = personal.getIdEstado();
        comboEstado.removeAllItems();
        
        for(int i = 0; i < listaEstado.size(); i++){
            comboEstado.addItem(listaEstado.get(i).getIdEstado());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApePat = new javax.swing.JTextField();
        txtApeMat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        txtAdscrip = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        txtFecNac = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtContract = new javax.swing.JTextField();
        txtPuesto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Jphoto = new javax.swing.JLabel();
        JpEstado = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTotalPersonal = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ApePat:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 100, -1));
        txtId.getAccessibleContext().setAccessibleName("");

        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, -1));

        txtApePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApePatActionPerformed(evt);
            }
        });
        jPanel2.add(txtApePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, -1));

        txtApeMat.setToolTipText("");
        txtApeMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApeMatActionPerformed(evt);
            }
        });
        jPanel2.add(txtApeMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 100, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ApeMat:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 56, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Curp:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 56, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adscripción:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        txtCurp.setName(""); // NOI18N
        jPanel2.add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 100, -1));

        txtAdscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdscripActionPerformed(evt);
            }
        });
        jPanel2.add(txtAdscrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 100, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FecNac:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sexo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estado:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });
        jPanel2.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 100, -1));

        txtFecNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecNacActionPerformed(evt);
            }
        });
        jPanel2.add(txtFecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 100, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contrato:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Puesto:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        txtContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContractActionPerformed(evt);
            }
        });
        jPanel2.add(txtContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 100, -1));
        jPanel2.add(txtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 100, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Foto:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        comboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoActionPerformed(evt);
            }
        });
        jPanel2.add(comboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 100, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 163, 23));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 163, 23));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 163, 23));

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 100, -1));

        Jphoto.setBackground(new java.awt.Color(153, 153, 153));
        Jphoto.setPreferredSize(new java.awt.Dimension(140, 140));
        jPanel2.add(Jphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 122, 142));

        JpEstado.setBackground(new java.awt.Color(153, 153, 153));
        JpEstado.setPreferredSize(new java.awt.Dimension(140, 140));
        jPanel2.add(JpEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 122, 142));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Perfil");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 43, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Estado");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 43, -1));

        jButton2.setText("Editar Estados");
        jButton2.setMaximumSize(new java.awt.Dimension(77, 22));
        jButton2.setMinimumSize(new java.awt.Dimension(77, 22));
        jButton2.setPreferredSize(new java.awt.Dimension(105, 22));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 163, 23));

        tbTotalPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTotalPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTotalPersonalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTotalPersonal);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 920, 260));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("APLICACION DE PERSONAL");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTotalPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTotalPersonalMouseClicked
       CPersonal objetoAlumno = new CPersonal();
       objetoAlumno.SeleccionarPersonal(tbTotalPersonal, txtId, txtNombre, txtApePat, 
               txtApeMat, txtCurp, txtAdscrip, txtContract, txtPuesto, 
               txtFecNac, txtSexo, comboEstado, Jphoto);
    }//GEN-LAST:event_tbTotalPersonalMouseClicked

    private void comboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoActionPerformed
        // Obtén el valor seleccionado en el JComboBox
        String idEstadoSeleccionado = comboEstado.getSelectedItem().toString();

        // Vuelve a llenar el JComboBox con los valores de la base de datos
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        CConexion objetoConexion = new CConexion();
        Connection conexion = objetoConexion.estableceConexion();

        if (conexion != null) {
            try {
                String sql = "SELECT idEstado FROM estados;";
                try (PreparedStatement preparedStatement = conexion.prepareStatement(sql);
                     ResultSet resultSet = preparedStatement.executeQuery()) {

                    while (resultSet.next()) {
                        String idEstado = resultSet.getString("idEstado");
                        comboBoxModel.addElement(idEstado);
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al llenar el combo de estados: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo establecer la conexión con la base de datos.");
        }
        
        objetoConexion.estableceConexion(); // Establece la conexión

        String sql = "SELECT fotoEstado FROM estados WHERE idEstado = ?";
        try (PreparedStatement preparedStatement = objetoConexion.prepareStatement(sql)) {
            preparedStatement.setString(1, idEstadoSeleccionado);

            try (ResultSet resultado = preparedStatement.executeQuery()) {
                if (resultado.next()) {
                    Blob imagenBlob = resultado.getBlob("fotoEstado");

                    if (imagenBlob != null) {
                        byte[] bytesImagen = imagenBlob.getBytes(1, (int) imagenBlob.length());
                        ImageIcon imagenOriginal = new ImageIcon(bytesImagen);
                        Image imagenEscalada = imagenOriginal.getImage()
                                .getScaledInstance(140, 140, Image.SCALE_SMOOTH);
                        // Supongamos que tienes un JLabel llamado jlabelFotoEstado
                        JpEstado.setIcon(new ImageIcon(imagenEscalada));
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al obtener la imagen del estado, error: " + e.toString());
        }
    }//GEN-LAST:event_comboEstadoActionPerformed

    private void txtContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContractActionPerformed

    private void txtAdscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdscripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdscripActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        CPersonal objetoAlumno = new CPersonal();
        objetoAlumno.EliminarPersonal(txtId);
        objetoAlumno.MostrarPersonal(tbTotalPersonal);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        byte[] imagenBytes = convertirImagenABytes(Jphoto);
        CPersonal objetoAlumno = new CPersonal();
        objetoAlumno.ModificarPersonal(txtId, txtNombre, txtApePat, txtApeMat, txtCurp,
            txtAdscrip, txtContract, txtPuesto, txtFecNac, txtSexo, 
            comboEstado, imagenBytes);
        objetoAlumno.MostrarPersonal(tbTotalPersonal);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        byte[] imagenBytes = convertirImagenABytes(Jphoto);
        CPersonal objetoAlumno = new CPersonal();
        objetoAlumno.InsertarPersonal(txtNombre, txtApePat, txtApeMat, txtCurp, txtAdscrip,
            txtContract, txtPuesto, txtFecNac, txtSexo, comboEstado, imagenBytes);
        objetoAlumno.MostrarPersonal(tbTotalPersonal);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtApeMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApeMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApeMatActionPerformed

    private void txtApePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApePatActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtFecNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecNacActionPerformed

    private byte[] convertirImagenABytes(JLabel label) {
    Icon icon = label.getIcon();
        if (icon instanceof ImageIcon) {
            BufferedImage imagen = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
            Graphics g = imagen.createGraphics();
            icon.paintIcon(label, g, 0, 0);
            g.dispose();

            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            try {
                ImageIO.write(imagen, "png", bos);
            } catch (IOException e) {
                e.printStackTrace();
            }
            return bos.toByteArray();
        }
        return null;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(140, 140, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            Jphoto.setIcon(icon);
            
        } catch (IOException ex){
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FormEstado panelEstado = new FormEstado();
        JFrame frame = new JFrame();
        frame.add(panelEstado);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JpEstado;
    private javax.swing.JLabel Jphoto;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTotalPersonal;
    private javax.swing.JTextField txtAdscrip;
    private javax.swing.JTextField txtApeMat;
    private javax.swing.JTextField txtApePat;
    private javax.swing.JTextField txtContract;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtFecNac;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
